### ISSUE TITLE
What is the blender version?

### ISSUE THREAD

**Issue by zz7379** [basilevh/carla-greater#1]
Thanks a lot for sharing the code!  My blender is 3.3 (I test 2.79b, got other error). When I run: 
`blender -b -P render_videos.py --num_cameras 3 --render_num_samples 32 --num_frames 300 --num_scenes 7000 --train_val_test_split 1 --random_camera_motion 0 --min_objects 8 --max_objects 12 --min_dist 0 --margin 0 --size_multiplier 2.0 --output_dir greater_4d/ --cpu 1 --speed_factor 1 --random_static_cameras 1
 --camera_radius 15 --any_containment 0 --vagabond_snitch 1 --start_index 0 --stop_index 100`
I got:
`Traceback (most recent call last):
  File "D:\DeepLearning\carla-greater-main\greater_mv\render_videos.py", line 486, in main
    render_scene(
  File "D:\DeepLearning\carla-greater-main\greater_mv\render_videos.py", line 679, in render_scene
    render_args.tile_x = args.render_tile_size
AttributeError: 'RenderSettings' object has no attribute 'tile_x'`
So I comment the lines, then got:
`RuntimeError: Error: The "filepath" property was not an absolute path: "greater_4d/train\GREATER_000000\blend.blend"`
I believe this is caused by mismatch of blender version. So could you please tell me your blender version?

**Comment by zz7379** [comment]
> Thanks a lot for sharing the code! My blender is 3.3 (I test 2.79b, got other error). When I run: `blender -b -P render_videos.py --num_cameras 3 --render_num_samples 32 --num_frames 300 --num_scenes 7000 --train_val_test_split 1 --random_camera_motion 0 --min_objects 8 --max_objects 12 --min_dist 0 --margin 0 --size_multiplier 2.0 --output_dir greater_4d/ --cpu 1 --speed_factor 1 --random_static_cameras 1 --camera_radius 15 --any_containment 0 --vagabond_snitch 1 --start_index 0 --stop_index 100` I got: `Traceback (most recent call last): File "D:\DeepLearning\carla-greater-main\greater_mv\render_videos.py", line 486, in main render_scene( File "D:\DeepLearning\carla-greater-main\greater_mv\render_videos.py", line 679, in render_scene render_args.tile_x = args.render_tile_size AttributeError: 'RenderSettings' object has no attribute 'tile_x'` So I comment the lines, then got: `RuntimeError: Error: The "filepath" property was not an absolute path: "greater_4d/train\GREATER_000000\blend.blend"` I believe this is caused by mismatch of blender version. So could you please tell me your blender version?

P.S. I use windows 10
